/**
 * TypeScript definitions for auki_pathfinding
 *
 * This file was automatically generated by uniffi-bindgen-wasm
 * Do not edit this file directly.
 */

/**
 * Function add
 * @param a - Parameter description
 * @param b - Parameter description
 */
export function add(
    a: number,
    b: number,
): number;

// WASM module initialization
export function initialize(): Promise<void>;