/**
 * Generated JavaScript bindings for auki_pathfinding
 *
 * This file was automatically generated by uniffi-bindgen-wasm
 * Do not edit this file directly.
 */

// Import WASM module
import init, * as wasm from './bridge_wasm.js';

// Type conversion helpers
const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();

function encodeString(str) {
    return textEncoder.encode(str);
}

function decodeString(bytes) {
    return textDecoder.decode(bytes);
}

function ensureBigInt(value) {
    return typeof value === 'bigint' ? value : BigInt(value);
}

// Converter registry for dynamic type lookup
const converterRegistry = {};

function registerConverter(name, converter) {
    converterRegistry[name] = converter;
    return converter;
}

function getConverter(typeName) {
    const converterName = `FfiConverter${typeName}`;
    return converterRegistry[converterName];
}

// RustBuffer infrastructure for complex type serialization
class RustBuffer {
    constructor(data) {
        if (data instanceof ArrayBuffer) {
            this.data = new DataView(data);
            this.byteArray = new Uint8Array(data);
        } else if (data instanceof Uint8Array) {
            this.data = new DataView(data.buffer, data.byteOffset, data.byteLength);
            this.byteArray = data;
        } else {
            // Create new buffer with given capacity
            const capacity = data || 0;
            const buffer = new ArrayBuffer(capacity);
            this.data = new DataView(buffer);
            this.byteArray = new Uint8Array(buffer);
        }
        this.offset = 0;
    }

    static fromByteArray(bytes) {
        return new RustBuffer(bytes);
    }

    static withCapacity(capacity) {
        return new RustBuffer(capacity);
    }

    readInt32() {
        const value = this.data.getInt32(this.offset, false); // big-endian (UniFFI default)
        this.offset += 4;
        return value;
    }

    writeInt32(value) {
        this.data.setInt32(this.offset, value, false); // big-endian (UniFFI default)
        this.offset += 4;
    }

    readInt64() {
        const value = this.data.getBigInt64(this.offset, false); // big-endian (UniFFI default)
        this.offset += 8;
        return value;
    }

    writeInt64(value) {
        this.data.setBigInt64(this.offset, BigInt(value), false); // big-endian (UniFFI default)
        this.offset += 8;
    }

    readByteArray(length) {
        const result = this.byteArray.slice(this.offset, this.offset + length);
        this.offset += length;
        return result;
    }

    writeByteArray(bytes) {
        this.byteArray.set(bytes, this.offset);
        this.offset += bytes.length;
    }

    get remainingCapacity() {
        return this.byteArray.length - this.offset;
    }
}

// FFI Converters for different types

// Boolean converter (u8 in UniFFI)
const FfiConverterBool = {
    read(buffer) {
        const value = buffer.data.getUint8(buffer.offset);
        buffer.offset += 1;
        return value !== 0;
    },
    write(value, buffer) {
        buffer.data.setUint8(buffer.offset, value ? 1 : 0);
        buffer.offset += 1;
    },
    allocationSize() {
        return 1;
    }
};

// Integer converters
const FfiConverterI8 = {
    read(buffer) {
        const value = buffer.data.getInt8(buffer.offset);
        buffer.offset += 1;
        return value;
    },
    write(value, buffer) {
        buffer.data.setInt8(buffer.offset, value);
        buffer.offset += 1;
    },
    allocationSize() {
        return 1;
    }
};

const FfiConverterU8 = {
    read(buffer) {
        const value = buffer.data.getUint8(buffer.offset);
        buffer.offset += 1;
        return value;
    },
    write(value, buffer) {
        buffer.data.setUint8(buffer.offset, value);
        buffer.offset += 1;
    },
    allocationSize() {
        return 1;
    }
};

const FfiConverterU16 = {
    read(buffer) {
        const value = buffer.data.getUint16(buffer.offset, false); // big-endian
        buffer.offset += 2;
        return value;
    },
    write(value, buffer) {
        buffer.data.setUint16(buffer.offset, value, false); // big-endian
        buffer.offset += 2;
    },
    allocationSize() {
        return 2;
    }
};

const FfiConverterU32 = {
    read(buffer) {
        const value = buffer.data.getUint32(buffer.offset, false); // big-endian
        buffer.offset += 4;
        return value;
    },
    write(value, buffer) {
        buffer.data.setUint32(buffer.offset, value, false); // big-endian
        buffer.offset += 4;
    },
    allocationSize() {
        return 4;
    }
};

const FfiConverterInt32 = {
    read(buffer) {
        return buffer.readInt32();
    },
    write(value, buffer) {
        buffer.writeInt32(value);
    },
    allocationSize() {
        return 4;
    }
};

const FfiConverterI64 = {
    read(buffer) {
        return buffer.readInt64();
    },
    write(value, buffer) {
        buffer.writeInt64(value);
    },
    allocationSize() {
        return 8;
    }
};

const FfiConverterU64 = {
    read(buffer) {
        const value = buffer.data.getBigUint64(buffer.offset, false); // big-endian
        buffer.offset += 8;
        return value;
    },
    write(value, buffer) {
        buffer.data.setBigUint64(buffer.offset, BigInt(value), false); // big-endian
        buffer.offset += 8;
    },
    allocationSize() {
        return 8;
    }
};

const FfiConverterF32 = {
    read(buffer) {
        const value = buffer.data.getFloat32(buffer.offset, false); // big-endian
        buffer.offset += 4;
        return value;
    },
    write(value, buffer) {
        buffer.data.setFloat32(buffer.offset, value, false); // big-endian
        buffer.offset += 4;
    },
    allocationSize() {
        return 4;
    }
};

const FfiConverterF64 = {
    read(buffer) {
        const value = buffer.data.getFloat64(buffer.offset, false); // big-endian
        buffer.offset += 8;
        return value;
    },
    write(value, buffer) {
        buffer.data.setFloat64(buffer.offset, value, false); // big-endian
        buffer.offset += 8;
    },
    allocationSize() {
        return 8;
    }
};

const FfiConverterString = {
    lift(bytes) {
        return decodeString(bytes);
    },
    lower(value) {
        return encodeString(value);
    },
    read(buffer) {
        const length = FfiConverterInt32.read(buffer);
        const bytes = buffer.readByteArray(length);
        return decodeString(bytes);
    },
    write(value, buffer) {
        const bytes = encodeString(value);
        FfiConverterInt32.write(bytes.length, buffer);
        buffer.writeByteArray(bytes);
    },
    allocationSize(value) {
        return FfiConverterInt32.allocationSize() + encodeString(value).length;
    }
};

/**
 * Function add
 * @param a - Parameter description
 * @param b - Parameter description
 * @returns Return value
 */
export function add(
    a,
    b,
) {
    const result = wasm.add(
        a,
        b,
    );
    return result;
}

// FFI converter for sequence types
const FfiConverterSequenceInt32 = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const length = FfiConverterInt32.read(from);
        const result = [];
        for (let i = 0; i < length; i++) {
            result.push(FfiConverterInt32.read(from));
        }
        return result;
    },
    write(value, into) {
        FfiConverterInt32.write(value.length, into);
        for (const item of value) {
            FfiConverterInt32.write(item, into);
        }
    },
    allocationSize(value) {
        return FfiConverterInt32.allocationSize() + (value.length * FfiConverterInt32.allocationSize());
    }
};

const FfiConverterSequenceString = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const length = FfiConverterInt32.read(from);
        const result = [];
        for (let i = 0; i < length; i++) {
            result.push(FfiConverterString.read(from));
        }
        return result;
    },
    write(value, into) {
        FfiConverterInt32.write(value.length, into);
        for (const item of value) {
            FfiConverterString.write(item, into);
        }
    },
    allocationSize(value) {
        let size = FfiConverterInt32.allocationSize();
        for (const item of value) {
            size += FfiConverterString.allocationSize(item);
        }
        return size;
    }
};

// FFI converter for optional types
const FfiConverterOptionalInt32 = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const flag = FfiConverterU8.read(from); // Option flag is u8, not i32!
        if (flag === 0) {
            return undefined;
        } else {
            return FfiConverterInt32.read(from);
        }
    },
    write(value, into) {
        if (value === undefined || value === null) {
            FfiConverterU8.write(0, into); // Option flag is u8!
        } else {
            FfiConverterU8.write(1, into); // Option flag is u8!
            FfiConverterInt32.write(value, into);
        }
    },
    allocationSize(value) {
        if (value === undefined || value === null) {
            return 1; // Just the flag byte
        } else {
            return 1 + FfiConverterInt32.allocationSize(); // flag + value
        }
    }
};

const FfiConverterOptionalString = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const flag = FfiConverterU8.read(from); // Option flag is u8, not i32!
        if (flag === 0) {
            return undefined;
        } else {
            return FfiConverterString.read(from);
        }
    },
    write(value, into) {
        if (value === undefined || value === null) {
            FfiConverterU8.write(0, into); // Option flag is u8!
        } else {
            FfiConverterU8.write(1, into); // Option flag is u8!
            FfiConverterString.write(value, into);
        }
    },
    allocationSize(value) {
        if (value === undefined || value === null) {
            return 1; // Just the flag byte
        } else {
            return 1 + FfiConverterString.allocationSize(value); // flag + value
        }
    }
};

// Generic optional converter for complex types (Records, Enums, primitives)
// Note: This reads the raw bytes WITHOUT a length prefix (UniFFI inlines the data)
const FfiConverterOptionalGeneric = {
    read(from) {
        const flag = FfiConverterU8.read(from);
        if (flag === 0) {
            return undefined;
        } else {
            // For generic optionals, we can't know the inner type here
            // This will need to be handled by the specific field readers
            // For now, return a placeholder that signals "Some" was read
            throw new Error('FfiConverterOptionalGeneric.read should not be called directly');
        }
    },
    write(value, into) {
        if (value === undefined || value === null) {
            FfiConverterU8.write(0, into);
        } else {
            FfiConverterU8.write(1, into);
            // Handle different value types - write directly inline (NO length prefix)
            const valueType = typeof value;
            
            if (value instanceof Uint8Array) {
                // Already serialized bytes - write inline
                into.writeByteArray(value);
            } else if (valueType === 'bigint') {
                // i64/u64 - write directly as 8 bytes
                into.writeInt64(value);
            } else if (valueType === 'number') {
                // Could be i32, f32, f64 - assume i64 for safety
                into.writeInt64(BigInt(Math.floor(value)));
            } else if (valueType === 'string') {
                // String has its own length prefix internally
                const bytes = FfiConverterString.lower(value);
                into.writeByteArray(bytes);
            } else if (value.constructor && value.constructor.name) {
                // Complex type (Record, Enum) - serialize and write inline
                const converter = getConverter(value.constructor.name);
                if (converter && converter.lower) {
                    const bytes = converter.lower(value);
                    into.writeByteArray(bytes);
                } else {
                    throw new Error(`No converter found for type ${value.constructor.name}`);
                }
            } else {
                throw new Error(`Cannot serialize value of unknown type`);
            }
        }
    },
    allocationSize(value) {
        if (value === undefined || value === null) {
            return 1; // Just the flag
        } else {
            const valueType = typeof value;
            
            if (value instanceof Uint8Array) {
                return 1 + value.length; // flag + inline bytes
            } else if (valueType === 'bigint') {
                return 1 + 8; // flag + 8 bytes for i64/u64
            } else if (valueType === 'number') {
                return 1 + 8; // flag + 8 bytes for i64 (conservative)
            } else if (valueType === 'string') {
                const bytes = FfiConverterString.lower(value);
                return 1 + bytes.length; // flag + string bytes (includes its own length internally)
            } else if (value.constructor && value.constructor.name) {
                const converter = getConverter(value.constructor.name);
                if (converter && converter.lower) {
                    const bytes = converter.lower(value);
                    return 1 + bytes.length; // flag + inline bytes
                } else {
                    throw new Error(`No converter found for type ${value.constructor.name}`);
                }
            } else {
                throw new Error(`Cannot serialize value of unknown type`);
            }
        }
    }
};

// Generic sequence converter for complex types
const FfiConverterSequenceGeneric = {
    read(from) {
        const length = FfiConverterInt32.read(from);
        const result = [];
        for (let i = 0; i < length; i++) {
            // For generic sequences, we can't deserialize without knowing the element type
            throw new Error('FfiConverterSequenceGeneric.read should not be called directly');
        }
        return result;
    },
    write(value, into) {
        FfiConverterInt32.write(value.length, into);
        for (const item of value) {
            const itemType = typeof item;
            
            if (item instanceof Uint8Array) {
                // Already serialized - write inline
                into.writeByteArray(item);
            } else if (itemType === 'bigint') {
                into.writeInt64(item);
            } else if (itemType === 'number') {
                into.writeInt64(BigInt(Math.floor(item)));
            } else if (itemType === 'string') {
                const bytes = FfiConverterString.lower(item);
                into.writeByteArray(bytes);
            } else if (item.constructor && item.constructor.name) {
                const converter = getConverter(item.constructor.name);
                if (converter && converter.lower) {
                    const bytes = converter.lower(item);
                    into.writeByteArray(bytes);
                } else {
                    throw new Error(`No converter found for type ${item.constructor.name}`);
                }
            } else {
                throw new Error(`Cannot serialize value of unknown type`);
            }
        }
    },
    allocationSize(value) {
        let size = 4; // length prefix
        for (const item of value) {
            const itemType = typeof item;
            
            if (item instanceof Uint8Array) {
                size += item.length;
            } else if (itemType === 'bigint') {
                size += 8;
            } else if (itemType === 'number') {
                size += 8;
            } else if (itemType === 'string') {
                const bytes = FfiConverterString.lower(item);
                size += bytes.length;
            } else if (item.constructor && item.constructor.name) {
                const converter = getConverter(item.constructor.name);
                if (converter && converter.lower) {
                    const bytes = converter.lower(item);
                    size += bytes.length;
                } else {
                    throw new Error(`No converter found for type ${item.constructor.name}`);
                }
            } else {
                throw new Error(`Cannot serialize value of unknown type`);
            }
        }
        return size;
    }
};

// FFI converter for map types
const FfiConverterMapStringInt32 = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const length = FfiConverterInt32.read(from);
        const result = {};
        for (let i = 0; i < length; i++) {
            const key = FfiConverterString.read(from);
            const value = FfiConverterInt32.read(from);
            result[key] = value;
        }
        return result;
    },
    write(value, into) {
        const entries = Object.entries(value);
        FfiConverterInt32.write(entries.length, into);
        for (const [key, val] of entries) {
            FfiConverterString.write(key, into);
            FfiConverterInt32.write(val, into);
        }
    },
    allocationSize(value) {
        let size = FfiConverterInt32.allocationSize();
        for (const [key, val] of Object.entries(value)) {
            size += FfiConverterString.allocationSize(key);
            size += FfiConverterInt32.allocationSize();
        }
        return size;
    }
};

const FfiConverterMapStringString = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        const length = FfiConverterInt32.read(from);
        const result = {};
        for (let i = 0; i < length; i++) {
            const key = FfiConverterString.read(from);
            const value = FfiConverterString.read(from);
            result[key] = value;
        }
        return result;
    },
    write(value, into) {
        const entries = Object.entries(value);
        FfiConverterInt32.write(entries.length, into);
        for (const [key, val] of entries) {
            FfiConverterString.write(key, into);
            FfiConverterString.write(val, into);
        }
    },
    allocationSize(value) {
        let size = FfiConverterInt32.allocationSize();
        for (const [key, val] of Object.entries(value)) {
            size += FfiConverterString.allocationSize(key);
            size += FfiConverterString.allocationSize(val);
        }
        return size;
    }
};

// Type-specific optional converters for i64/u64
const FfiConverterOptionalI64 = {
    read(from) {
        const flag = FfiConverterU8.read(from);
        if (flag === 0) {
            return undefined;
        } else {
            return FfiConverterI64.read(from);
        }
    },
    write(value, into) {
        if (value === undefined || value === null) {
            FfiConverterU8.write(0, into);
        } else {
            FfiConverterU8.write(1, into);
            FfiConverterI64.write(value, into);
        }
    },
    allocationSize(value) {
        return (value === undefined || value === null) ? 1 : 9; // flag + 8 bytes
    }
};

const FfiConverterOptionalU64 = {
    read(from) {
        const flag = FfiConverterU8.read(from);
        if (flag === 0) {
            return undefined;
        } else {
            return FfiConverterU64.read(from);
        }
    },
    write(value, into) {
        if (value === undefined || value === null) {
            FfiConverterU8.write(0, into);
        } else {
            FfiConverterU8.write(1, into);
            FfiConverterU64.write(value, into);
        }
    },
    allocationSize(value) {
        return (value === undefined || value === null) ? 1 : 9; // flag + 8 bytes
    }
};

// FFI converter for Duration
const FfiConverterDuration = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        // Duration is u64 secs + u32 nanos (big-endian)
        const secs = from.data.getBigUint64(from.offset, false);
        from.offset += 8;
        const nanos = from.data.getUint32(from.offset, false);
        from.offset += 4;
        return { secs, nanos };
    },
    write(value, into) {
        // Duration is u64 secs + u32 nanos (big-endian)
        into.data.setBigUint64(into.offset, BigInt(value.secs || 0), false);
        into.offset += 8;
        into.data.setUint32(into.offset, value.nanos || 0, false);
        into.offset += 4;
    },
    allocationSize(value) {
        return 12; // u64 + u32
    }
};

// FFI converter for Timestamp
const FfiConverterTimestamp = {
    lift(bytes) {
        const buffer = RustBuffer.fromByteArray(bytes);
        return this.read(buffer);
    },
    lower(value) {
        const buffer = RustBuffer.withCapacity(this.allocationSize(value));
        this.write(value, buffer);
        // Return just the bytes up to the current offset
        return buffer.byteArray.slice(0, buffer.offset);
    },
    read(from) {
        // Timestamp is u64 secs + u32 nanos (big-endian)
        const secs = from.data.getBigUint64(from.offset, false);
        from.offset += 8;
        const nanos = from.data.getUint32(from.offset, false);
        from.offset += 4;
        return { secs, nanos };
    },
    write(value, into) {
        // Timestamp is u64 secs + u32 nanos (big-endian)
        into.data.setBigUint64(into.offset, BigInt(value.secs || 0), false);
        into.offset += 8;
        into.data.setUint32(into.offset, value.nanos || 0, false);
        into.offset += 4;
    },
    allocationSize(value) {
        return 12; // u64 + u32
    }
};

// Async polling infrastructure for Rust futures
const UNIFFI_RUST_FUTURE_POLL_READY = 0;
const UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1;

class UniffiHandleMap {
    constructor() {
        this.map = new Map();
        this.currentHandle = BigInt(0);
    }

    insert(value) {
        this.map.set(this.currentHandle, value);
        return this.currentHandle++;
    }

    get(handle) {
        const obj = this.map.get(handle);
        if (obj === undefined) {
            throw new Error(`Handle ${handle} not found in handle map`);
        }
        return obj;
    }

    remove(handle) {
        const obj = this.map.get(handle);
        if (obj !== undefined) {
            this.map.delete(handle);
        }
        return obj;
    }

    has(handle) {
        return this.map.has(handle);
    }

    get size() {
        return this.map.size;
    }
}

// The resolver handle map contains the resolvers from each of the pollRust promises
const UNIFFI_RUST_FUTURE_RESOLVER_MAP = new UniffiHandleMap();

// pollRust makes a new promise, stores the resolver in the resolver map,
// then calls the pollFunc with the handle
async function pollRust(pollFunc) {
    return new Promise((resolve) => {
        const handle = UNIFFI_RUST_FUTURE_RESOLVER_MAP.insert(resolve);
        pollFunc(handle);
    });
}

// Rust calls this callback, which resolves the promise returned by pollRust
// This needs to be converted to a function pointer for WASM
function uniffiFutureContinuationCallback(handle, pollResult) {
    const resolve = UNIFFI_RUST_FUTURE_RESOLVER_MAP.remove(handle);
    if (resolve) {
        resolve(pollResult);
    }
}

// Expose the continuation callback globally so the WASM runtime can invoke it
globalThis.__uniffiFutureContinuation = uniffiFutureContinuationCallback;

// Simple UniffiRustCaller for making Rust calls
const uniffiCaller = {
    rustCall: (caller, liftString) => {
        return caller();
    },
    rustCallWithError: (liftError, caller, liftString) => {
        return caller();
    }
};

/**
 * This function calls an asynchronous method on the Rust side.
 * It manages the polling between JS promises and Rust futures.
 */
async function uniffiRustCallAsync(
    rustCaller,
    rustFutureFunc,
    pollFunc,
    cancelFunc,
    completeFunc,
    freeFunc,
    liftFunc,
    liftString,
    asyncOpts
) {
    // Check if should bail early due to abort signal
    if (asyncOpts?.signal?.aborted === true) {
        return Promise.reject(new Error('Operation aborted'));
    }

    // Call into the Rust method to get the future handle
    const rustFuture = rustFutureFunc();

    const abortFunc = () => cancelFunc(rustFuture);
    asyncOpts?.signal?.addEventListener('abort', abortFunc);

    try {
        let pollResult;
        do {
            // Poll the Rust future until it's ready
            pollResult = await pollRust((handle) => {
                pollFunc(rustFuture, handle);
            });
        } while (pollResult !== UNIFFI_RUST_FUTURE_POLL_READY);

        // Now it's ready, get the result
        return liftFunc(
            rustCaller.rustCall(
                () => completeFunc(rustFuture),
                liftString
            )
        );
    } finally {
        // Clean up
        asyncOpts?.signal?.removeEventListener('abort', abortFunc);
        freeFunc(rustFuture);
    }
}

/**
 * Initialize the WASM module
 * path - optional path to the .wasm file
 * @returns {Promise<void>}
 */
export async function initialize(path) {
    await init(path);
}

// Auto-initialize if in browser environment
if (typeof window !== 'undefined') {
    initialize().catch(console.error);
}